export default {
  userBorderBox: true,
  breakpoints: ['320px', '600px', '960px', '1280px', '1920px', '2560px'],
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fonts: {
    body:
      'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: 'Inter, sans-serif',
    monospace: 'Overpass Mono, monospace',
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 96],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#053c5e',
    dark: '#001634',
    secondary: '#db222a',
    muted: '#f6f6f6',
  },
  shadows: [
    'none',
    '0px 2px 1px -1px rgba(0,0,0,0.2),0px 1px 1px 0px rgba(0,0,0,0.14),0px 1px 3px 0px rgba(0,0,0,0.12)',
    '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
    '0px 3px 5px -1px rgba(0,0,0,0.2),0px 5px 8px 0px rgba(0,0,0,0.14),0px 1px 14px 0px rgba(0,0,0,0.12)',
    '0px 4px 5px -2px rgba(0,0,0,0.2),0px 7px 10px 1px rgba(0,0,0,0.14),0px 2px 16px 1px rgba(0,0,0,0.12)',
    '0px 6px 7px -4px rgba(0,0,0,0.2),0px 11px 15px 1px rgba(0,0,0,0.14),0px 4px 20px 3px rgba(0,0,0,0.12)',
    '0px 7px 8px -4px rgba(0,0,0,0.2),0px 13px 19px 2px rgba(0,0,0,0.14),0px 5px 24px 4px rgba(0,0,0,0.12)',
    '0px 8px 9px -5px rgba(0,0,0,0.2),0px 15px 22px 2px rgba(0,0,0,0.14),0px 6px 28px 5px rgba(0,0,0,0.12)',
    '0px 8px 11px -5px rgba(0,0,0,0.2),0px 17px 26px 2px rgba(0,0,0,0.14),0px 6px 32px 5px rgba(0,0,0,0.12)',
    '0px 9px 12px -6px rgba(0,0,0,0.2),0px 19px 29px 2px rgba(0,0,0,0.14),0px 7px 36px 6px rgba(0,0,0,0.12)',
    '0px 10px 13px -6px rgba(0,0,0,0.2),0px 21px 33px 3px rgba(0,0,0,0.14),0px 8px 40px 7px rgba(0,0,0,0.12)',
    '0px 11px 14px -7px rgba(0,0,0,0.2),0px 23px 36px 3px rgba(0,0,0,0.14),0px 9px 44px 8px rgba(0,0,0,0.12)',
  ],
  borders: ['1px solid #2c4247', '.4px solid lightgray'],
  radii: ['4px', '6px', '8px', '12px'],
  text: {
    subtitle: {
      fontSize: 2,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      opacity: 0.55,
    },
    body: {
      lineHeight: 1.6,
      opacity: 0.9,
      fontSize: 3,
    },
    postPreview: {
      lineHeight: 1.8,
      opacity: 0.9,
      fontSize: 3,
    },
    postPreviewLink: {
      textDecoration: 'none',
      textTransform: 'uppercase',
      letterSpacing: '1px',
      display: 'block',
      width: 'fit-content',
      marginLeft: 'auto',
      marginRight: 'auto',
      cursor: 'pointer',
      fontWeight: 500,
      fontSize: 3,
    },
    landingButtonLink: {
      textDecoration: 'none',
      letterSpacing: '1px',
      display: 'block',
      cursor: 'pointer',
      fontWeight: 500,
      fontSize: 3,
      color: 'white',
      backgroundColor: '#00011',
      textAlign: 'center',
      px: 4,
      py: 2,
      border: '.4px solid #fff',
      borderRadius: 2,
    },
  },
  headings: {
    h1: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [6, 6, 6, 6, 6],
    },
    h2: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [5, 5, 5, 5, 5],
    },
    h3: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [4, 4, 4, 4, 4],
    },
    h4: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [3, 3, 3, 3, 3],
    },
    h5: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [2, 2, 2, 2, 2],
    },
    h6: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: [1, 1, 1, 1, 1],
    },
  },
  forms: {
    fieldContainer: {
      padding: 2,
      paddingLeft: 0,
      marginBottom: 1,
    },
    label: {
      pb: 1,
      fontSize: [3],
    },
    input: {
      fontFamily: 'body',
      fontSize: [3],
      outline: 0,
      border: 1,
      transition: 'all 0.2s',
      borderRadius: 1,
      '&:focus': {
        zIndex: 1,
        background: 'transparent',
        boxShadow: `0 0 0 2px #07c`,
      },
    },
    radio: {
      '&:hover': {
        backgroundColor: '#07c7',
      },
    },
  },
  buttons: {
    contained: {
      border: 'none',
      display: 'inline-block',
      cursor: 'pointer',
      minWidth: '100px',
      padding: 2,
      textAlign: 'center',
      textDecoration: 'none',
      fontSize: [3],
      fontFamily: 'monospace',
      borderRadius: 0,
      color: 'white',
      boxShadow: 1,
      backgroundColor: 'primary',
      transition: 'all .222s cubic-bezier(0.4, 0, 1, 1)',
      '&:hover': {
        backgroundColor: 'dark',
        boxShadow: 2,
        transform: 'translateY(-1px)',
      },
      '&:focus': {
        backgroundColor: 'dark',
        boxShadow: 2,
      },
    },
  },
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      a: {
        color: 'primary',
      },
    },
    hr: {
      height: '1px',
      background: 'lightgray',
      opacity: 0.6,
      border: 'inherit',
    },
    h1: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 6,
    },
    h2: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 4,
    },
    h3: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 3,
    },
    h4: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 2,
    },
    h5: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 1,
    },
    h6: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 0,
    },
    p: {
      color: 'text',
      fontFamily: 'body',
      fontWeight: 'body',
      lineHeight: 'body',
    },
    a: {
      color: 'primary',
    },
    pre: {
      fontFamily: 'monospace',
      overflowX: 'auto',
      code: {
        color: 'inherit',
      },
    },
    code: {
      fontFamily: 'monospace',
      fontSize: 'inherit',
    },
    table: {
      width: '100%',
      borderCollapse: 'separate',
      borderSpacing: 0,
    },
    th: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    td: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    img: {
      maxWidth: '100%',
    },
  },
};
